### PR TITLE
add dispatch exception functions

### PR DESCRIPTION
**Pull request by tinygiant98**

### CODE REVIEW

**Comment by squattingmonk** [comment]
I like the idea of this but there's a couple of implementation details I think need to be resolved:

1. Should it only be `oInit` that is checked for an exception? Ideally, if the builder doesn't want `oSelf` to run the event, they won't attach the event handler to the object. But there may be cases like timers where there is no event handler.
2. I like that this can be treated as an event blacklist or whitelist. It looks like setting an event to be whitelisted deletes any blacklist and vice versa. I think the purpose of the functions might be clearer if we rename them. Perhaps `GetEventBlacklisted()`, `SetEventsBlacklisted()`, and `ClearEventBlacklist()` and matching whitelist functions?
3. I like being able to pass a CSV list do handle multiple events with one call. However, storing the events in a varlist requires checking each event in turn until the desired one is found. A better solution may be:
    - Just store an int for each event that should be bypassed. Then it just requires a single lookup.
    - Alternatively, store the events in a CSV list. Iterating through a string list to compare items is faster than sequentially getting and comparing local strings.
    - You could also combine both methods: use a CSV list for the whitelist/blacklist and store an int for each event in the list. The int is the one that is checked during `RunEvent()`; the CSV list can just be used to keep track of which events are blacklisted if the user clears it or switches to a whitelist.

**Comment by tinygiant98** [comment]
Good comments.  I'll go through and try to improve the code.  Here's a few answers to your concerns:
1.  `oSelf` is probably the right answer.  Using `oInit` likely resulted from a misinterpreation of the debug messages I was getting when I was deciding between `oSelf` and `oInit`.

2.  Good point with the procedure names.  I named them when I was originally going to implement a dispatch exception (blacklist) only.  After I'd finished the initial coding, it became apparent that I needed to add a whitelist option, that's why it seems like the whitelist portion was an afterthought -- it was.

3.  Agreed on the CSV.  I'm already in the middle of modifying to use CSV instead of varlist for the same reasons you listed.  I'll press into it over the next few days and see what I can come up with.  Thanks for the review!

**Comment by squattingmonk** [comment]
`oInit` is the object that triggers the event. In events like OnHeartbeat, it's `oSelf`, but in events like OnCreaturePerception, it's the object being perceived. So if you were to blacklist OnCreaturePerception on object A with the current system:
1. If A is `OBJECT_SELF`, the event will still run.
2. If A is `oInit`, the event will be bypassed. The blacklist is basically saying "Don't run this event when you see me".

However, if we check `oSelf` for the blacklist:
1. if A is `OBJECT_SELF`, the event will not run.
2. If A is `oInit`, the event will run.

I could see cases where you would want either behavior. The current behavior seems more broadly useful. For example, you might want to blacklist OnAreaEnter for a creature, in which case the creature is `oInit`. We just need to make it clear when the event will actually be bypassed.

**Comment by tinygiant98** [comment]
Makes sense.  So it seems like we have to decide whether we want our object to block events he perpetrates (oInit) or events perpetrated on him (oSelf).  Seems like most would be ones that he receives (oSelf), as in all the creature events, but depending on the case, you might want a little of either.  For example, if you have an NPC that you don't want any events to run on, you'd want him as oSelf for creature events, but oInit for area events.  Time to put some more thinks into this one.  Guess it depends on how simple the system needs to be.

**Comment by tinygiant98** [comment]
Seems the greatest benefit of this system, in basic form, would be if we assumed the object would be `oInit`.  Since the primary purpose of objects in the game is to interact with the PC, you'd want objects to have their events fire when they're interacted with, but likely don't want those objects to initiate events on other objects (such as NPCs perceiving each other or entering areas).  Although the system could be greatly expanded to include key:value pairs based on when the object acts as `oInit` or `oSelf`, I think it's better to keep the system simple for now and just assume the object acts as `oInit`.  Another consideration, or at least a check, could be that if either the `oInit` or the `oSelf` is  a PC, the event always fires, which would prevent issues such as events not firing if an NPC kills a PC.  I'm going to press in that direction, let me know if you have any additional input.

**Comment by tinygiant98** [comment]
Ok, next iteration is up.  This one a bit more ambitious than the first, setting up dispatch levels instead of just exceptions.  Includes support for white/blacklist, module-wide override settings and builder-friendly function wrappers.  Still not ready for primetime ... ;ots of extraneous comments to explain flow.  They'll be removed when the system is ready.  Review appreciated!

**Pull request merged**
