### PR TITLE
Add time include to utilities

### PR DESCRIPTION
**Pull request by tinygiant98**
Some general time manipulation functions.  Let me know if you think they're usable for inclusion in the framework and, if so, what kind of feedback you have for them.  Thanks!

### CODE REVIEW

**Comment by tinygiant98** [comment]
Added the state comparison fix for `hook_module14.nss`

**Comment by squattingmonk** [comment]
Could you make that fix a separate PR since they are different things?

**Comment by tinygiant98** [comment]
Yup, sorry, had them on the same branch since it was a quick fix. I'll try to get to it tonight.

**Comment by tinygiant98** [comment]
Closing incorrectly created PR.

**Pull request closed without merging**
