### PR TITLE
fixed changed event sources not firing scripts

### PR DESCRIPTION
**Pull request by tinygiant98**
We found specific scripts were not being run when they were added via `AddScriptSource` in `core_i_framework`.  Maybe not the best way to ensure they run, but this modification resets the variables that marks the scripts as collected, forcing them to recollect them from the script sources, thus allowing newly-added script sources to provide their scripts to the framework.

### CODE REVIEW

**Comment by squattingmonk** [comment]
I'm confused by how this would help. `CacheEventSources` sets that variable to `FALSE` already. Deleting it would not have a different effect. The debug line would be helpful, though.

**Comment by tinygiant98** [comment]
Yep, I must've missed that. When I discovered that changes sources weren't being included, it needed to be fixed pretty quick.  I don't think i revisited it after first draft.   After review, looks like the line in question can be deleted. I'll update when I get near a computer later tonight.   Good catch.

**Comment by tinygiant98** [comment]
Removed the extra DeleteLocalInt call and slightly modified the debug feedback statement.

**Comment by tinygiant98** [comment]
Pulling merge request until this can be investigated.

**Pull request closed without merging**
